// FONTS
import { Inter } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] });

// CSS
import '@/styles/globals.scss';

// Context Provider
import ContextProvider from '@/context/context-provider';

// Components
import CartTrigger from '@/components/Commerce/CartTrigger';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ContextProvider>
          <header>
            <CartTrigger />
          </header>
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}
